[tool.poetry]
name = "sergiy-mil"
version = "0.0.1"
description = "MILP solver"
authors = [
  "Sergiy Yarygin sergiyar55@gmail.com",
  "Alexey Savinov schet.v.komplax@gmail.com"
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.pyright]
include = "src"

